### ISSUE TITLE
ip whitelist

### ISSUE THREAD

**Issue by rvpn** [mkrou/smartdns#1]
are you planning to add a support for whitelisting ip ?

current setup means whoever have the DNS IP can freely use it without having to be authorized first right?

**Comment by mkrou** [comment]
You're right. I've been thinking about it. I haven't figured out how to make this check simple. In the end I decided that the chance that someone will use your dns is extremely small.

**Comment by mkrou** [comment]
I added the option to add IP to the white list. You can use the variable ALLOWED_IP for this purpose.
